Repository boostcampwm-2024/web23-Pinoco, pull requests merged in 2024-12, with the labels that each got.

#206 [Feat] 게임 대기 중 준비 상태를 플레이어 모두가 공유하는 기능 추가
  packages/frontend/src/components/gamePage/leftSection/GameButtons/ReadyButton.tsx
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/components/gamePage/leftSection/VideoFeed.tsx
  packages/frontend/src/hooks/useReadyStatus.ts
  packages/frontend/src/hooks/useSpeakingControl.ts
Labels: 작업 중, FE

#211 [Feat] 방 제한 인원 / 탭 연결 끊었을 때 나가기 기능 구현
  packages/backend/signalingServer/src/handlers/handleSignaling.ts
  packages/backend/signalingServer/src/handlers/handleSocket.ts
  packages/frontend/src/hooks/useJoinRoom.ts
  packages/frontend/src/states/store/peerConnectionStore.ts
  packages/frontend/src/states/store/signalingSocketStore.ts
Labels: 작업 완료, FE, BE

#216 [Feat] 사용자는 로비 페이지에서 미디어 장치를 변경할 수 있다.
  packages/frontend/src/assets/images/DropBoxArrowDown.svg
  packages/frontend/src/assets/images/DropBoxArrowUp.svg
  packages/frontend/src/components/gamePage/stream/MediaSourcePicker.tsx
  packages/frontend/src/components/lobbyPage/DropBox.tsx
  packages/frontend/src/components/lobbyPage/VideoAudioTestModal.tsx
  packages/frontend/src/store/localStreamStore.ts
  packages/frontend/src/utils/videoStreamUtils.ts
Labels: 작업 완료, FE

#215 [Feat] private, public route 설정
  packages/frontend/src/App.tsx
  packages/frontend/src/components/PrivateRoute.tsx
  packages/frontend/src/components/PublicRoute.tsx
  packages/frontend/src/pages/gamePage/index.tsx
  packages/frontend/src/pages/landingPage/index.tsx
  packages/frontend/src/pages/lobbyPage/index.tsx
  packages/frontend/src/routes/router.tsx
Labels: 작업 완료, FE

#218 [Feat] 준비 로직 리팩토링
  packages/frontend/src/components/gamePage/leftSection/VideoFeed.tsx
  packages/frontend/src/components/lobbyPage/GameEntryModal.tsx
  packages/frontend/src/hooks/useGameSocket.ts
  packages/frontend/src/hooks/useReadyStatus.ts
  packages/frontend/src/store/roomStore.ts
Labels: 작업 완료, FE

#223 [Chore] 게임 메뉴얼 및 이미지 수정
  packages/frontend/index.html
  packages/frontend/public/favicon.png
  packages/frontend/public/images/gameManual/manu3.png
  packages/frontend/public/images/gameManual/manu4.png
  packages/frontend/public/images/gameManual/manu5.png
  packages/frontend/public/images/gameManual/manu6.png
  packages/frontend/public/images/gameManual/manu7.png
  packages/frontend/public/images/gameManual/manu8.png
  packages/frontend/public/images/videoStream/videoPoster.png
  packages/frontend/public/images/videoStream/videoPoster2.png
  packages/frontend/src/components/gamePage/GameManual.tsx
Labels: 작업 완료, FE

#226 [Feat] 방장 표시 기능 구현
  packages/frontend/public/images/videoStream/videoPoster.png
  packages/frontend/src/components/gamePage/leftSection/GameButtons/ReadyButton.tsx
  packages/frontend/src/components/gamePage/leftSection/VideoFeed.tsx
  packages/frontend/src/components/gamePage/rightSection/LeaveButton.tsx
  packages/frontend/src/hooks/useChatSocket.ts
  packages/frontend/src/hooks/useCreateRoom.ts
  packages/frontend/src/hooks/useJoinRoom.ts
  packages/frontend/src/pages/lobbyPage/index.tsx
  packages/frontend/src/store/roomStore.ts
Labels: 작업 완료, FE

#227 [Refactor] 프론트엔드 성능 개선
  packages/frontend/src/App.tsx
  packages/frontend/src/assets/fonts/Pretendard-Bold.woff
  packages/frontend/src/assets/fonts/Pretendard-Medium.woff
  packages/frontend/src/assets/fonts/Pretendard-Regular.woff
  packages/frontend/src/assets/fonts/Pretendard-SemiBold.woff
  packages/frontend/src/components/common/LoadingSpinner.tsx
  packages/frontend/src/components/gamePage/leftSection/GamePhases/Voting.tsx
  packages/frontend/src/components/gamePage/leftSection/GuessInput.tsx
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/components/gamePage/leftSection/VideoFeed.tsx
  packages/frontend/src/hooks/useGameSocket.ts
  packages/frontend/src/index.css
  packages/frontend/src/main.tsx
  packages/frontend/src/routes/router.tsx
  packages/frontend/src/store/roomStore.ts
Labels: 작업 완료, FE

#228 [Refactor] 게임서버 모듈, 계층 리팩토링
  packages/backend/gameserver/src/app.module.ts
  packages/backend/gameserver/src/chat/chat.module.ts
  packages/backend/gameserver/src/chat/chat.service.ts
  packages/backend/gameserver/src/filters/ws-exception.filter.ts
  packages/backend/gameserver/src/game/game.service.ts
  packages/backend/gameserver/src/game/types/game.types.ts
  packages/backend/gameserver/src/gateway/gateway.gateway.ts
  packages/backend/gameserver/src/gateway/gateway.module.ts
  packages/backend/gameserver/src/gateway/gateway.service.ts
  packages/backend/gameserver/src/room/room.service.ts
  packages/backend/gameserver/src/room/types/room.types.ts
  packages/backend/gameserver/src/types/socket.types.ts
Labels: 작업 완료, BE
