Repository boostcampwm-2024/web23-Pinoco, pull requests merged in 2024-11, with the labels that each got.

#61 [Design] 디자인 시스템 수정
  .prettierrc
  packages/frontend/src/components/gamePage/rightSection/ChatSection.tsx
  packages/frontend/src/components/gamePage/rightSection/RightGameSection.tsx
  packages/frontend/tailwind.config.js
Labels: 작업 완료, FE

#59 [Feat] 공통 컴포넌트 모달 파일 생성
  packages/frontend/index.html
  packages/frontend/src/components/common/Modal.tsx
  packages/frontend/src/components/lobbyPage/RoomJoinButton.tsx
  packages/frontend/src/hooks/useModal.ts
Labels: 작업 완료

#63 [Feat] 게임 참가하기 모달 추가
  packages/frontend/src/components/lobbyPage/RoomJoinButton.tsx
  packages/frontend/src/pages/lobbyPage/index.tsx
Labels: 작업 완료

#73 [Feat] 비회원 로그인 추가
  packages/frontend/src/apis/index.tsx
  packages/frontend/src/apis/instance.ts
  packages/frontend/src/apis/login.ts
  packages/frontend/src/components/landingPage/GuestLoginButton.tsx
  packages/frontend/src/states/store/authStore.ts
  packages/frontend/src/states/store/index.tsx
Labels: 작업 완료, FE

#78 [Design] Header UI 수정
  packages/frontend/src/assets/images/Bell.svg
  packages/frontend/src/assets/images/Friends.svg
  packages/frontend/src/components/layout/Header.tsx
  packages/frontend/src/pages/gamePage/index.tsx
  packages/frontend/src/pages/lobbyPage/index.tsx
Labels: 작업 완료, FE

#88 [Feat] 채팅 로직 구현
  packages/frontend/src/components/gamePage/rightSection/ChatSection.tsx
  packages/frontend/src/hooks/useChatSocket.ts
  packages/frontend/src/states/store/chatStore.ts
Labels: 작업 완료, FE

#89 [Fix] 채팅 관련 msw 로직 삭제
  packages/frontend/src/mocks/handlers.ts
Labels: 작업 완료, FE

#98 [Fix] Socket 연결 방식 수정
  packages/frontend/src/App.tsx
  packages/frontend/src/apis/instance.ts
  packages/frontend/src/apis/login.ts
  packages/frontend/src/components/common/Modal.tsx
  packages/frontend/src/components/gamePage/rightSection/ChatSection.tsx
  packages/frontend/src/components/landingPage/GuestLoginButton.tsx
  packages/frontend/src/hooks/useChatSocket.ts
  packages/frontend/src/hooks/useCreateRoom.ts
  packages/frontend/src/hooks/useJoinRoom.ts
  packages/frontend/src/pages/landingPage/index.tsx
  packages/frontend/src/pages/lobbyPage/index.tsx
  packages/frontend/src/states/store/authStore.ts
  packages/frontend/src/states/store/chatStore.ts
  packages/frontend/src/states/store/roomStore.ts
  packages/frontend/src/states/store/socketStore.ts
Labels: 작업 완료, FE

#100 [Fix] 수정된 api 명세에 따른 채팅 로직 수정
  packages/frontend/src/components/gamePage/rightSection/ChatSection.tsx
  packages/frontend/src/hooks/useChatSocket.ts
  packages/frontend/src/states/store/chatStore.ts
Labels: 작업 완료, FE

#101 [Chore] 코드 품질 검사, 빌드 자동화를 위한 CI 세팅
  .eslintrc.js
  .github/workflows/ci.yml
  .pnp.cjs
  packages/backend/gameserver/.eslintrc.js
  packages/backend/package.json
  packages/frontend/eslint.config.js
  packages/frontend/package.json
  packages/frontend/src/components/layout/BackgroundImage.tsx
  packages/frontend/src/hooks/useChatSocket.ts
  yarn.lock
Labels: 작업 완료

#110 [Feat] 방 생성, 참가 로직 게임서버와 연동
  packages/frontend/src/components/layout/BackgroundImage.tsx
  packages/frontend/src/components/lobbyPage/GameEntryModal.tsx
  packages/frontend/src/components/lobbyPage/RoomJoinButton.tsx
  packages/frontend/src/hooks/useCreateRoom.ts
  packages/frontend/src/hooks/useJoinRoom.ts
  packages/frontend/vite.config.ts
Labels: 작업 완료, FE

#109 [Feat] 카운트다운 및 제시어 화면 구현
  packages/frontend/src/components/gamePage/leftSection/GameButtons/ReadyButton.tsx
  packages/frontend/src/components/gamePage/leftSection/GameButtons/StartButton.tsx
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/components/gamePage/leftSection/Timer.tsx
  packages/frontend/src/constants/index.tsx
Labels: 작업 완료, FE

#113 [Chore] CI 설정 완료
  .github/workflows/ci.yml
Labels: 작업 완료

#97 [Feat] WebRTC 시그널링 서버 구현
  .gitignore
  .pnp.cjs
  .yarn/cache/has-flag-npm-3.0.0-16ac11fe05-1c6c83b14b.zip
  .yarn/cache/ignore-by-default-npm-1.0.1-78ea10bc54-9ab6e70e80.zip
  .yarn/cache/nodemon-npm-3.1.7-ef86478222-e0b46939ab.zip
  .yarn/cache/pstree.remy-npm-1.1.8-2dd5d55de2-30f78c88ce.zip
  .yarn/cache/simple-update-notifier-npm-2.0.0-4d6e5dba61-2a00bd03bf.zip
  .yarn/cache/supports-color-npm-5.5.0-183ac537bc-6ae5ff319b.zip
  .yarn/cache/touch-npm-3.1.1-30ecbeb0ee-d2e4d269a4.zip
  .yarn/cache/undefsafe-npm-2.0.5-8c3bbf9354-96c0466a5f.zip
  packages/backend/signalingServer/README.md
  packages/backend/signalingServer/package.json
  packages/backend/signalingServer/src/app.ts
  packages/backend/signalingServer/src/constants/roomConstants.ts
  packages/backend/signalingServer/src/constants/serverConstants.ts
  packages/backend/signalingServer/src/constants/socketConstants.ts
  packages/backend/signalingServer/src/handlers/handleRoom.ts
  packages/backend/signalingServer/src/handlers/handleSignaling.ts
  packages/backend/signalingServer/src/handlers/handleSocket.ts
  packages/backend/signalingServer/src/middleware/cors.ts
  packages/backend/signalingServer/src/socket/initSocket.ts
  packages/backend/signalingServer/src/types/signaling.types.ts
  packages/backend/signalingServer/tsconfig.json
  packages/backend/signalingServer/tsconfig.tsbuildinfo
  yarn.lock
Labels: 작업 완료

#116 [Fix] 채팅 연결 로직 수정
  packages/frontend/src/App.tsx
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/components/gamePage/rightSection/SettingSection.tsx
  packages/frontend/src/components/landingPage/GuestLoginButton.tsx
  packages/frontend/src/components/layout/PrivateRoute.tsx
  packages/frontend/src/components/layout/PublicRoute.tsx
  packages/frontend/src/components/lobbyPage/GameEntryModal.tsx
  packages/frontend/src/hooks/useChatSocket.ts
  packages/frontend/src/hooks/useCreateRoom.ts
  packages/frontend/src/hooks/useJoinRoom.ts
  packages/frontend/src/pages/landingPage/index.tsx
  packages/frontend/src/pages/lobbyPage/index.tsx
  packages/frontend/src/routes/router.tsx
  packages/frontend/src/states/store/roomStore.ts
  packages/frontend/src/states/store/socketStore.ts
Labels: 작업 완료, FE

#118 [Feat] 시그널링 서버 HTTPS 설정 추가
  packages/backend/signalingServer/docker-compose.yml
  packages/backend/signalingServer/src/app.ts
Labels: 작업 완료, BE

#123 [Fix] Private, Public route 삭제
  packages/frontend/src/components/layout/PrivateRoute.tsx
  packages/frontend/src/components/layout/PublicRoute.tsx
  packages/frontend/src/routes/router.tsx
  packages/frontend/src/states/store/roomStore.ts
Labels: 작업 완료, FE

#122 [Feat] 시그널링 서버 연결
  packages/backend/signalingServer/src/constants/roomConstants.ts
  packages/backend/signalingServer/src/handlers/handleRoom.ts
  packages/backend/signalingServer/src/handlers/handleSignaling.ts
  packages/backend/signalingServer/src/types/signaling.types.ts
  packages/backend/signalingServer/src/util/handlerUtils.ts
  packages/backend/signalingServer/src/util/logUtils.ts
  packages/frontend/src/components/landingPage/GuestLoginButton.tsx
  packages/frontend/src/hooks/useCreateRoom.ts
  packages/frontend/src/hooks/useJoinRoom.ts
  packages/frontend/src/states/store/signalingSocketStore.ts
Labels: 작업 완료, FE, BE

#127 [Feat] 게임 로직 반영
  packages/frontend/src/components/gamePage/leftSection/GameButtons/ReadyButton.tsx
  packages/frontend/src/components/gamePage/leftSection/GameButtons/StartButton.tsx
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/components/gamePage/rightSection/SettingSection.tsx
  packages/frontend/src/constants/index.tsx
  packages/frontend/src/hooks/useCreateRoom.ts
  packages/frontend/src/hooks/useGameSocket.ts
  packages/frontend/src/hooks/useJoinRoom.ts
  packages/frontend/src/states/store/roomStore.ts
Labels: 작업 완료, FE

#129 [Feat] 피노코가 제시어를 맞추는 GUESSING 페이즈 구현
  packages/frontend/src/components/gamePage/leftSection/GuessInput.tsx
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/hooks/useGuessing.ts
Labels: 작업 완료, FE

#131 [Feat] 게임 결과를 보여주는 ENDING 페이즈 구현
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/hooks/useEnding.ts
Labels: 작업 완료, FE

#133 [Feat] receive_vote_result에 따라 투표 결과를 보여주고, 다음 페이즈로 이동하는 로직 구현
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/hooks/useVoteResult.ts
Labels: 작업 완료, FE

#142 [Chore] VITE 환경 변수 설정
  .github/workflows/ci.yml
  packages/frontend/src/apis/instance.ts
  packages/frontend/src/states/store/socketStore.ts
Labels: 작업 완료

#145 [Design] 타이머 위치 수정
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
Labels: 작업 완료, FE

#153 [Fix] 전체 유저 목록이 잘 반영되도록 수정
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/hooks/useChatSocket.ts
  packages/frontend/src/hooks/useCreateRoom.ts
  packages/frontend/src/hooks/useJoinRoom.ts
  packages/frontend/src/pages/gamePage/index.tsx
  packages/frontend/src/states/store/roomStore.ts
Labels: 작업 완료, FE

#156 [Feat] 게임로직 구현 완료
  packages/backend/gameserver/src/auth/auth.service.ts
  packages/backend/gameserver/src/game/game.service.ts
  packages/backend/gameserver/src/game/types/game.types.ts
  packages/backend/gameserver/src/gateway/gateway.gateway.ts
  packages/backend/gameserver/src/gateway/gateway.service.ts
Labels: BE

#155 [Fix] 투표 결과 관련 에러 해결
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/constants/index.tsx
  packages/frontend/src/hooks/useEnding.ts
  packages/frontend/src/hooks/useGameSocket.ts
  packages/frontend/src/hooks/useGuessing.ts
  packages/frontend/src/hooks/useVoteResult.ts
Labels: 작업 완료, FE

#163 [Fix] 한글 입력 시 마지막 글자가 중복 전송되는 문제 해결
  packages/frontend/src/components/gamePage/rightSection/ChatSection.tsx
Labels: 작업 완료, FE

#167 [Fix] 게임페이지에서 로비페이지 이동시에 방 Id가 존재한다면 해당 사용자에 대해 leave_room 처리
  packages/frontend/src/pages/lobbyPage/index.tsx
Labels: 작업 완료, FE

#169 [Feat] 탈락한 사람에 대한 UI 수정
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
Labels: 작업 완료, FE

#171 [Feat] 채팅 영역 UX 개선
  packages/frontend/src/assets/images/ArrowDownIcon.svg
  packages/frontend/src/components/gamePage/rightSection/ChatSection.tsx
  packages/frontend/src/constants/chatState.ts
  packages/frontend/src/hooks/useChatSocket.ts
  packages/frontend/src/states/store/chatStore.ts
Labels: 작업 완료, FE

#172 [Feat] 로비 페이지 방문 상태 관리 및 툴팁 추가
  .pnp.cjs
  .yarn/cache/@floating-ui-core-npm-1.6.8-496cdfbb6e-d6985462ae.zip
  .yarn/cache/@floating-ui-dom-npm-1.6.12-4d4284e824-c67b398621.zip
  .yarn/cache/@floating-ui-utils-npm-0.2.8-01a00634a5-a8cee5f174.zip
  .yarn/cache/classnames-npm-2.5.1-c7273f3423-afff4f77e6.zip
  .yarn/cache/fsevents-patch-6b67494872-10c0.zip
  .yarn/cache/react-tooltip-npm-5.28.0-a698d2e4f8-817909584a.zip
  package.json
  packages/frontend/package.json
  packages/frontend/src/components/landingPage/GuestLoginButton.tsx
  packages/frontend/src/components/lobbyPage/GameEntryModal.tsx
  packages/frontend/src/components/lobbyPage/RoomCreationButton.tsx
  packages/frontend/src/utils/firstVisitManager.ts
  packages/frontend/src/utils/index.tsx
  packages/frontend/vite.config.ts
  yarn.lock
Labels: 작업 완료, FE

#180 [Design] 게임 로직 UI 개선
  packages/frontend/src/components/gamePage/leftSection/Countdown.tsx
  packages/frontend/src/components/gamePage/leftSection/GamePhases/EndingResult.tsx
  packages/frontend/src/components/gamePage/leftSection/GamePhases/VoteResult.tsx
  packages/frontend/src/components/gamePage/leftSection/GamePhases/Voting.tsx
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/components/gamePage/leftSection/WordDisplay.tsx
  packages/frontend/src/hooks/useGameSocket.ts
Labels: 작업 완료, FE

#179 [Feat] 게임 첫 접속 시에 띄워줄 게임 메뉴얼 모달 구현
  packages/frontend/src/assets/images/manual/1.png
  packages/frontend/src/assets/images/manual/2.png
  packages/frontend/src/assets/images/manual/3.png
  packages/frontend/src/assets/images/manual/HowToPlayLogo.png
  packages/frontend/src/components/gamePage/GameManual.tsx
  packages/frontend/src/components/landingPage/GuestLoginButton.tsx
  packages/frontend/src/pages/gamePage/index.tsx
Labels: 작업 완료, FE

#176 [Feat] 사용자는 webRTC를 통해 원활히 통신할 수 있다.
  packages/backend/coturnServer/turnserver.conf
  packages/backend/signalingServer/src/handlers/handleSignaling.ts
  packages/backend/signalingServer/src/types/signaling.types.ts
  packages/backend/signalingServer/src/util/handlerUtils.ts
  packages/backend/signalingServer/src/util/logUtils.ts
  packages/backend/signalingServer/yarn.lock
  packages/frontend/public/images/videoPoster.png
  packages/frontend/public/images/videoPoster2.png
  packages/frontend/src/components/gamePage/rightSection/SettingSection.tsx
  packages/frontend/src/components/gamePage/stream/VideoStream.tsx
  packages/frontend/src/states/store/peerConnectionStore.ts
Labels: 작업 완료, BE

#178 [Feat] 투표, 게임시작 관련 서버측 로직 변경
  packages/backend/gameserver/src/game/constants/words.ts
  packages/backend/gameserver/src/game/game.service.ts
  packages/backend/gameserver/src/gateway/gateway.gateway.ts
Labels: bug, 작업 완료, BE

#183 [Feat] 투표 결과 무효표 처리 & 탈락자 역할 공개 로직 추가
  packages/frontend/src/components/gamePage/leftSection/GamePhases/VoteResult.tsx
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
Labels: 작업 완료, FE

#184 [Feat] 발화자의 비디오가 메인 디스플레이에 보이는 기능
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/components/gamePage/stream/VideoStream.tsx
  packages/frontend/src/states/store/signalingSocketStore.ts
Labels: 작업 완료, FE

#186 [Feat] 사용자 비디오 비율 개선
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
  packages/frontend/src/components/gamePage/leftSection/VideoFeed.tsx
  packages/frontend/src/components/gamePage/stream/VideoStream.tsx
  packages/frontend/src/pages/gamePage/index.tsx
Labels: 작업 완료, FE

#189 [Chore] public 이미지 경로 수정
  packages/frontend/public/images/gameManual/1.png
  packages/frontend/public/images/gameManual/2.png
  packages/frontend/public/images/gameManual/3.png
  packages/frontend/public/images/gameManual/HowToPlayLogo.png
  packages/frontend/public/images/videoStream/videoPoster.png
  packages/frontend/public/images/videoStream/videoPoster2.png
  packages/frontend/src/components/gamePage/GameManual.tsx
  packages/frontend/src/components/gamePage/stream/VideoStream.tsx
Labels: 작업 완료, FE

#190 [Feat] 오디오/비디오 버튼 토글 제어 기능 구현
  packages/frontend/src/assets/images/CameraOff.svg
  packages/frontend/src/assets/images/CameraOn.svg
  packages/frontend/src/assets/images/Leave.svg
  packages/frontend/src/assets/images/MikeOff.svg
  packages/frontend/src/assets/images/MikeOn.svg
  packages/frontend/src/components/gamePage/rightSection/CameraSettingButton.tsx
  packages/frontend/src/components/gamePage/rightSection/LeaveButton.tsx
  packages/frontend/src/components/gamePage/rightSection/MikeSettingButton.tsx
  packages/frontend/src/components/gamePage/rightSection/SettingSection.tsx
Labels: 작업 완료, FE, BE

#193 [Feat] 게임 결과 화면 구성
  packages/frontend/public/images/ending/geppettoWin.png
  packages/frontend/public/images/ending/pinocoWin.png
  packages/frontend/src/components/gamePage/leftSection/GamePhases/EndingResult.tsx
  packages/frontend/src/components/gamePage/leftSection/MainDisplay.tsx
Labels: 작업 완료, FE

#195 [Feat] 비디오 / 오디오 테스트 기능 추가
  packages/frontend/src/assets/images/CameraOff.svg
  packages/frontend/src/assets/images/CameraOn.svg
  packages/frontend/src/assets/images/MikeOff.svg
  packages/frontend/src/assets/images/MikeOn.svg
  packages/frontend/src/components/gamePage/rightSection/SettingSection.tsx
  packages/frontend/src/components/gamePage/stream/CameraSettingButton.tsx
  packages/frontend/src/components/gamePage/stream/MikeSettingButton.tsx
  packages/frontend/src/components/lobbyPage/SettingSection.tsx
  packages/frontend/src/components/lobbyPage/VideoAudioTestButton.tsx
  packages/frontend/src/components/lobbyPage/VideoAudioTestModal.tsx
  packages/frontend/src/pages/lobbyPage/index.tsx
  packages/frontend/src/states/store/signalingSocketStore.ts
Labels: 작업 완료, FE, BE

#196 [Feat] 각종 버그 수정 및 로그인시 클라측에서 id받는 로직 추가
  packages/backend/gameserver/src/auth/auth.controller.ts
  packages/backend/gameserver/src/auth/auth.service.ts
  packages/backend/gameserver/src/game/constants/words.ts
  packages/backend/gameserver/src/game/game.service.ts
  packages/backend/gameserver/src/gateway/gateway.gateway.ts
  packages/backend/gameserver/src/room/room.service.ts
  packages/backend/gameserver/src/room/types/room.types.ts
Labels: 작업 완료, BE

#197 [Feat] 게스트 로그인에서의 닉네임 설정 구현
  packages/frontend/src/apis/login.ts
  packages/frontend/src/components/landingPage/GuestLoginButton.tsx
  packages/frontend/src/components/landingPage/NicknameModal.tsx
Labels: 작업 완료, FE

#198 [Fix] 타이머 기능 개선
  packages/frontend/src/components/gamePage/leftSection/Timer.tsx
Labels: 작업 완료, FE
